version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    container_name: desafio-backend-app-prod
    restart: unless-stopped
    env_file:
      - .env
    command: >
      sh -c "
        php artisan migrate --force &&
        php-fpm
      "
    volumes:
      - app_code_prod:/var/www
    networks:
      - desafio-net-prod

  nginx:
    image: nginx:alpine
    container_name: desafio-backend-nginx-prod
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_code_prod:/var/www:ro
    depends_on:
      - app
    networks:
      - desafio-net-prod

  db:
    image: mysql:8.0
    container_name: desafio-backend-db-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db_data_prod:/var/lib/mysql
    networks:
      - desafio-net-prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    container_name: desafio-frontend-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - desafio-net-prod

networks:
  desafio-net-prod:
    driver: bridge

volumes:
  db_data_prod:
  app_code_prod: